//Nome: Nicolas Paris - Cartao: 302650
#pragma once
#define AST_DEC_LIST        1
#define AST_VAR_DEC         2
#define AST_FUNC_DEC        3
#define AST_VEC_DEC         4
#define AST_PARAM_LIST      5
#define AST_PARAM           6
#define AST_BLOCK           7
#define AST_COMMAND_LIST    8
#define AST_ASSIGNMENT      9
#define AST_VEC_ASSIGNMENT  10
#define AST_IDENTIFIER      11
#define AST_LITERAL         12
#define AST_EXPR_LIST       13
#define AST_ADD             14
#define AST_SUB             15
#define AST_MUL             16
#define AST_DIV             17
#define AST_LES             18
#define AST_GRE             19
#define AST_OR              20
#define AST_AND             21
#define AST_LE              22
#define AST_GE              23
#define AST_EQ              24
#define AST_DIF             25
#define AST_NOT             26
#define AST_VEC_ACESS       27
#define AST_FUNC_CALL       28
#define AST_READ            29
#define AST_PRINT           30
#define AST_STRING          31
#define AST_PARENTHESIS     32
#define AST_VEC_READ        33
#define AST_RETURN          34
#define AST_WHILE           35
#define AST_IF              36
#define AST_IF_ELSE         37
#define AST_CHAR            38
#define AST_INT             39
#define AST_FLOAT           40
#define AST_SYMBOL          41
#define AST_LITERAL_LIST    42
#define AST_EXPR            43