//Nome: Nicolas Paris - Cartao: 302650
#define AST_DEC             1
#define AST_VAR_DEC         2
#define AST_FUNC_DEC        3
#define AST_VEC_DEC         4
#define AST_PARAM_LIST      5
#define AST_PARAM           6
#define AST_BLOCK           7
#define AST_COMMAND         8
#define AST_ASSIGNMENT      9
#define AST_VEC_ASSIGNMENT  10
#define AST_IDENTIER        11
#define AST_LITERAL         12
#define AST_EXPR            13
#define AST_ADD             14
#define AST_SUB             15
#define AST_MUL             16
#define AST_DIV             17
#define AST_LES             18
#define AST_GRE             19
#define AST_OR              20
#define AST_AND             21
#define AST_LE              22
#define AST_GE              23
#define AST_EQ              24
#define AST_DIF             25
#define AST_NOT             26
#define AST_CHAR            50
#define AST_INT             51
#define AST_FLOAT           52
#define AST_SYMBOL          66
#define AST_LITERAL_LIST    67